site_name: 2386 Programming
nav:
  - Home: "docs/index.md"
  - Rationale: 
    - About: "docs/rationale.md"
    - Detection: "docs/rationale_detection.md"
    - Dashboard: "docs/rationale_dashboard.md"
theme:
  name: 'windmill-dark'
  custom_dir: 'mkdocs-windmill-dark/mkdocs_windmill_dark'
