site_name: 2386 Programming
site_url: https://bchrobotics.github.io/documentation/
use_directory_urls: true

extra:
  base_path: /documentation/

nav:
  - Home: index.md
  - Guides:
      - Object Detection: 
          - Overview: g_object-detection.md
          - Color Banding: g_color-banding.md
          - Neural Networks: g_neural-nets.md

  
theme:
  name: 'windmill-dark'
  custom_dir: 'mkdocs-windmill-dark/mkdocs_windmill_dark'


# mkdocs build -f ./documentation/mkdocs.yml
