site_name: 2386 Programming
site_url: https://bchrobotics.github.io/documentation/
use_directory_urls: true

extra:
  base_path: /documentation/

nav:
  - Home: index.md

  - List of Known Issues: known-issues.md

  - Guides:
      - The Basics:
          - Downloading FRC Software: g_software-downloads.md
          - Making A Robot Project: g_new-project.md
          - Using Drivetools: g_drivetools.md
      - Object Detection: 
          - Overview: g_object-detection.md
          - Color Banding: g_color-banding.md
          - Neural Networks: g_neural-nets.md
          - Advanced Approaches: g_advanced-od.md
      - Vision:
          - Overview: g_vision.md
          - Photonvision Setup: g_photon-setup.md
      - Hardware:
          - Configuring SparkMAXs: g_hardware-config.md
          - Swerve Modules: g_swerve-modules.md
          - Swerve Drive Math: g_swerve-math.md


  
theme:
  name: 'windmill-dark'
  custom_dir: 'mkdocs-windmill-dark/mkdocs_windmill_dark'


# mkdocs build -f ./documentation/mkdocs.yml
