site_name: 2386 Programming
site_url: https://bchrobotics.github.io/documentation/
use_directory_urls: true

extra:
  base_path: /documentation/

nav:
  - Home: index.md

  - List of Known Issues: known-issues.md

  - Competition Checklist: comp-checklist.md

  - Guides:
      - The Basics:
          - Overview: g_basics-overview.md
          - Conventions: g_conventions.md
          - Downloading FRC Software: g_software-downloads.md
          - Making A Robot Project: g_new-project.md
          - Running Robot Code: g_running-code.md
          - Using Drivetools: g_drivetools.md
          - Commands: g_commands.md
      - Vision:
          - Overview: g_vision.md
          - Photonvision Setup: g_photon-setup.md
          - Object Detection: 
            - Overview: g_object-detection.md
            - Color Banding: g_color-banding.md
            - Neural Networks: g_neural-nets.md
            - Advanced Approaches: g_advanced-od.md
          - Apriltags:
            - Overview: g_apriltags.md
            - Pose Estimation: g_pose-estimation.md
      - Hardware:
          - Configuring SparkMAXs: g_hardware-config.md
          - Swerve Modules: g_swerve-modules.md
          - Swerve Drive Math: g_swerve-math.md
      - At Competition:
          - Preparing: g_comp-preparation.md


  
theme:
  name: 'windmill-dark'
  custom_dir: 'mkdocs-windmill-dark/mkdocs_windmill_dark'


# mkdocs build -f ./documentation/mkdocs.yml
